import com.v7878.zygisk.gradle.ZygoteLoader

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.java.zygisk)
}

android {
    namespace 'com.v7878.hooks.pmpatch'
    compileSdk 36

    defaultConfig {
        minSdk 26
        targetSdk 36
        versionCode 1_002_001
        versionName "v1.2.1"

        buildConfigField("boolean", "RUN_FOR_APPLICATIONS", "false")
        buildConfigField("boolean", "RUN_FOR_SYSTEM_SERVER", "true")

        ndk {
            abiFilters 'arm64-v8a', 'x86_64'
        }
    }

    buildFeatures {
        buildConfig = true
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles 'proguard-rules.pro'
        }
        debug {
            debuggable true
            minifyEnabled false
            shrinkResources false
        }
    }

    flavorDimensions += ["patch"]
    productFlavors {
        patch12 {
            dimension "patch"

            zygisk {
                packages(ZygoteLoader.ALL_PACKAGES)

                id = "com_v7878_pmpatch"
                name = "PMPatch-Core"
                archiveName = "PMPatch-Core"
            }

            buildConfigField("boolean", "PATCH_1", "true")
            buildConfigField("boolean", "PATCH_2", "true")
            buildConfigField("boolean", "PATCH_3", "false")
            buildConfigField("boolean", "USE_CONFIG", "false")
        }
        patch3 {
            dimension "patch"

            zygisk {
                packages(ZygoteLoader.PACKAGE_SYSTEM_SERVER)

                id = "com_v7878_pmpatch"
                name = "PMPatch-PM"
                archiveName = "PMPatch-PM"
            }

            buildConfigField("boolean", "PATCH_1", "false")
            buildConfigField("boolean", "PATCH_2", "false")
            buildConfigField("boolean", "PATCH_3", "true")
            buildConfigField("boolean", "USE_CONFIG", "false")
        }
        full {
            dimension "patch"

            zygisk {
                packages(ZygoteLoader.ALL_PACKAGES)

                id = "com_v7878_pmpatch"
                name = "PMPatch-All"
                archiveName = "PMPatch-All"
            }

            buildConfigField("boolean", "PATCH_1", "true")
            buildConfigField("boolean", "PATCH_2", "true")
            buildConfigField("boolean", "PATCH_3", "true")
            buildConfigField("boolean", "USE_CONFIG", "false")
        }
        // Configurable version where you can enable and disable
        // any of the patches without rebuilding (exists specifically for LuckyPatcher)
        LP {
            dimension "patch"

            zygisk {
                packages(ZygoteLoader.ALL_PACKAGES)

                property("PATCH_1", "true")
                property("PATCH_2", "true")
                property("PATCH_3", "true")

                id = "com_v7878_pmpatch"
                name = "PMPatch-LP"
                archiveName = "PMPatch-LP"
            }

            buildConfigField("boolean", "PATCH_1", "true")
            buildConfigField("boolean", "PATCH_2", "true")
            buildConfigField("boolean", "PATCH_3", "true")
            buildConfigField("boolean", "USE_CONFIG", "true")
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

zygisk {
    author = "v7878, People11"
    description = "Disable signature verification For Android"
    entrypoint = "com.v7878.hooks.pmpatch.Main"
    attachNativeLibs = false
    generateChecksums = true
}

dependencies {
    implementation libs.androidvmtools
    implementation libs.r8.annotations
}

configurations.configureEach {
    exclude group: 'com.github.vova7878', module: 'R8Annotations'
}
