[versions]
agp = "9.1.0"
zygisk = "358a146d87"
r8_annotations = "v1.0.1"
androidvmtools = "335b118dbb"

[libraries]
androidvmtools = { module = "com.github.vova7878:AndroidVMTools", version.ref = "androidvmtools" }
r8-annotations = { module = "io.github.vova7878:R8Annotations", version.ref = "r8_annotations" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
java-zygisk = { id = "com.github.vova7878.ZygoteLoader", version.ref = "zygisk" }
